
###########
# site.url, site.title

title: 'DASH BOWL'
url: 'https://kroc702.github.io/dashbowl'
baseurl: '/dashbowl'

discordurl: 'https://discord.gg/kH43mSsqZ'
githuburl: 'https://github.com/kroc702/dashbowl'

plugins:
- jekyll-sitemap
# - jekyll-last-modified-at unfortunately don't work in github

defaults:
- scope:
    path: ''
  values:
    lang: en
    langpath: ''
- scope:
    path: 'fr'
  values:
    lang: fr
    langpath: 'fr/'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- preview.bat
- Gemfile

safe: true
lsi: false