
###########
# site.url, site.title

title: 'DASH BOWL'
url: 'https://kroc702.github.io/dashbowl'
baseurl: '/dashbowl'

discordurl: 'https://discord.gg/kH43mSsqZ'

plugins:
- jekyll-sitemap

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- preview.bat
- Gemfile

safe: true
lsi: false