name: Generate Rules PDF

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/generate-pdf.yml'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y weasyprint
          pip install markdown weasyprint python-frontmatter

      - name: Generate html with Python script
        run: python .github/scripts/md2html.py en
      - name: Generate PDF with Python script
        run: python .github/scripts/html2pdf.py release/dashbowl_en
      - name: Generate fr html with Python script
        run: python .github/scripts/md2html.py fr
      - name: Generate fr PDF with Python script
        run: python .github/scripts/html2pdf.py release/dashbowl_fr

      - name: Upload en PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashbowl-en
          path: release/dashbowl_en.pdf
      - name: Upload fr PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashbowl-fr
          path: release/dashbowl_fr.pdf
